flask-base/app/models/youtube.py
import datetime

from .. import db


class Channel(db.Model):
    name = db.Column(db.String(100), unique=False)
    channelId = db.Column(db.String(100), unique=True, primary_key=True)
    description = db.Column(db.Text)
    videos = db.relationship(
        'Video', backref=db.backref('channel', lazy='joined'), lazy='select')

    def __repr__(self):
        return '<%r>' % self.name


tags = db.Table(
    'tags',
    db.Column('tag_id', db.Integer, db.ForeignKey('tag.id'), primary_key=True),
    db.Column(
        'video_id', db.Integer, db.ForeignKey('video.id'), primary_key=True))


class Video(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), unique=False)
    videoId = db.Column(db.String(100), unique=True, nullable=False)
    tags = db.relationship(
        'Tag',
        secondary=tags,
        lazy='joined',
        backref=db.backref('pages', lazy='joined'))
    channelId = db.Column(db.String(100), db.ForeignKey('channel.channelId'))
    thumbnail = db.Column(db.String(300))
    publishedAt = db.Column(db.DateTime, nullable=False)
    description = db.Column(db.Text)
    stats = db.relationship(
        'Stats', backref=db.backref('video', lazy=True), lazy='select')

    def __repr__(self):
        return '<%r>' % self.title


class Stats(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    videoId = db.Column(db.Integer, db.ForeignKey('video.id'), nullable=False)
    viewCount = db.Column(db.Integer)
    commentCount = db.Column(db.Integer)
    likeCount = db.Column(db.Integer)
    dislikeCount = db.Column(db.Integer)
    favoriteCount = db.Column(db.Integer)
    date = db.Column(
        db.DateTime, nullable=False, default=datetime.datetime.utcnow)


class Tag(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    tagname = db.Column(db.String(100), unique=True)

flask-base/app/youtube/__init__.py
from app.youtube.views import youtube  # noqa

flask-base/app/youtube/views.py
import json

import wtforms as wt
from flask import Blueprint, Response, render_template, request
from flask_wtf import Form
from wtforms import TextField

from app import db
from app.models import Tag, Video

youtube = Blueprint('youtube', __name__)


class FilterForm(Form):
    autocomp = TextField('Filter by tags', id='autocomplete')


@youtube.route('/autocomplete', methods=['GET'])
def autocomplete():
    search = request.args.get('term', '')
    tags = [
        tag.tagname
        for tag in Tag.query.filter(Tag.tagname.like(search + '%')).all()
    ]
    return Response(json.dumps(tags), mimetype='application/json')


@youtube.route('/dashboard', methods=['GET', 'POST'])
def dashboard():
    """display collected data"""
    form = FilterForm(request.form)
    if request.method == 'POST':
        if form.autocomp.data == '':
            videos = Video.query.all()
        else:
            tag = Tag.query.filter_by(tagname=form.autocomp.data).first()
            if tag:
                videos = Video.query.filter(Video.tags.any(id=tag.id)).all()
            else:
                videos = []

    if request.method == 'GET':
        videos = Video.query.all()
    return render_template('youtube/dashboard.html', videos=videos, form=form)

flask-base/app/templates/youtube/dashboard.html
{% extends 'layouts/base.html' %}
{% import 'macros/form_macros.html' as f %}

{% block custom_head_tags %}
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
{% endblock %}

{% block content %}

    <div class="ui grid container">
        <div class="eight wide computer sixteen wide mobile centered column">
            <h2 class="ui dividing header">Filter videos:</h2>

            {% set flashes = {
                'error':   get_flashed_messages(category_filter=['form-error']),
                'warning': get_flashed_messages(category_filter=['form-check-email']),
                'info':    get_flashed_messages(category_filter=['form-info']),
                'success': get_flashed_messages(category_filter=['form-success'])
            } %}

            {{ f.begin_form(form, flashes) }}

            <div class="two fields">
                {{ f.render_form_field(form.autocomp) }}
            </div>


            {{ f.form_message(flashes['error'], header='Something went wrong.', class='error') }}
            {{ f.form_message(flashes['warning'], header='Check your email.', class='warning') }}
            {{ f.form_message(flashes['info'], header='Information', class='info') }}
            {{ f.form_message(flashes['success'], header='Success!', class='success') }}

            {% for field in form | selectattr('type', 'equalto', 'SubmitField') %}
                {{ f.render_form_field(field) }}
            {% endfor %}

            {{ f.end_form(form) }}

            <p>
              <label for="amount">Performance range (views number divided by average channel views number * 100):</label>
              <input type="text" id="amount" readonly style="border:0; color:#f6931f; font-weight:bold;">
            </p>

            <div id="slider-range"></div>
            <h1>Videos</h1>
            <br>
            <br>
            {% for video in videos %}
            <div class="video">
                <h4>{{ video.title}}</h4>
                <img src="{{ video.thumbnail }}" alt="{{ video.title }}"/>
                <p>performance: </p>
            </div>
            {% endfor %}
        </div>
    </div>


    <script>
    $(function() {
        $.ajax({
            url: '{{ url_for("youtube.autocomplete") }}'
            }).done(function (data) {
                $('#autocomplete').autocomplete({
                    source: data,
                    minLength: 2
                });
            });
        });
    </script>

    <script>
      $( function() {
        $( "#slider-range" ).slider({
          range: true,
          min: 0,
          max: 100,
          values: [ 50, 80 ],
          slide: function( event, ui ) {
            $( "#amount" ).val( "$" + ui.values[ 0 ] + " - $" + ui.values[ 1 ] );
          }
        });
        $( "#amount" ).val( "$" + $( "#slider-range" ).slider( "values", 0 ) +
          " - $" + $( "#slider-range" ).slider( "values", 1 ) );
      } );
    </script>
{% endblock %}